In [1]:
import pandas as pd

In [14]:
df_train = pd.read_csv("train.csv", index_col = "Id")
df_test = pd.read_csv("test.csv", index_col = "Id")

df_train_55_79 = df_train[df_train.columns[55:-1]]
df_test_55_79 = df_test[df_test.columns[55:-1]]

display(df_train_55_79.shape, df_test_55_79.shape)

display(df_train_55_79.head(), df_test_55_79.head())

(1460, 24)

(1459, 23)

,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
2,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
3,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
4,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
5,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,...,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType
Id,,,,,,,,,,,,,,,,,,,,,
1461,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,...,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD
1462,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,...,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD
1463,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,...,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD
1464,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,...,0,0,0,NaN,NaN,NaN,0,6,2010,WD
1465,0,NaN,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,...,0,144,0,NaN,NaN,NaN,0,1,2010,WD

In [15]:
display(df_train_55_79.info(), df_test_55_79.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 1 to 1460
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Fireplaces     1460 non-null   int64
 1   FireplaceQu    770 non-null    object
 2   GarageType     1379 non-null   object
 3   GarageYrBlt    1379 non-null   float64
 4   GarageFinish   1379 non-null   object
 5   GarageCars     1460 non-null   int64
 6   GarageArea     1460 non-null   int64
 7   GarageQual     1379 non-null   object
 8   GarageCond     1379 non-null   object
 9   PavedDrive     1460 non-null   object
 10  WoodDeckSF     1460 non-null   int64
 11  OpenPorchSF    1460 non-null   int64
 12  EnclosedPorch  1460 non-null   int64
 13  3SsnPorch      1460 non-null   int64
 14  ScreenPorch    1460 non-null   int64
 15  PoolArea       1460 non-null   int64
 16  PoolQC         7 non-null      object
 17  Fence          281 non-null    object
 18  MiscFeature    54 non-null     object
 19  MiscVal        1460 non-null   int64
 20  MoSold         1460 non-null   int64
 21  YrSold         1460 non-null   int64
 22  SaleType       1460 non-null   object
 23  SaleCondition  1460 non-null   object
dtypes: float64(1), int64(12), object(11)
memory usage: 285.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1459 entries, 1461 to 2919
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Fireplaces     1459 non-null   int64
 1   FireplaceQu    729 non-null    object
 2   GarageType     1383 non-null   object
 3   GarageYrBlt    1381 non-null   float64
 4   GarageFinish   1381 non-null   object
 5   GarageCars     1458 non-null   float64
 6   GarageArea     1458 non-null   float64
 7   GarageQual     1381 non-null   object
 8   GarageCond     1381 non-null   object
 9   PavedDrive     1459 non-null   object
 10  WoodDeckSF     1459 non-null   int64
 11  OpenPorchSF    1459 non-null   int64
 12  EnclosedPorch  1459 non-null   int64
 13  3SsnPorch      1459 non-null   int64
 14  ScreenPorch    1459 non-null   int64
 15  PoolArea       1459 non-null   int64
 16  PoolQC         3 non-null      object
 17  Fence          290 non-null    object
 18  MiscFeature    51 non-null     object
 19  MiscVal        1459 non-null   int64
 20  MoSold         1459 non-null   int64
 21  YrSold         1459 non-null   int64
 22  SaleType       1458 non-null   object
dtypes: float64(3), int64(10), object(10)
memory usage: 273.6+ KB

None

None

**Check for real NaN!**

In [16]:
display(df_train_55_79.isna().sum(), df_test_55_79.isna().sum())

Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
dtype: int64

Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond         78
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1456
Fence            1169
MiscFeature      1408
MiscVal             0
MoSold              0
YrSold              0
SaleType            1
dtype: int64

## Data Description
* Fireplaces: Number of fireplaces  > *"fireplace_number" / numeric / integer*
* FireplaceQu: Fireplace quality > *"fireplace_quality" / categorical / ordinal*

>       Ex	Excellent - Exceptional Masonry Fireplace > (5)
>       Gd	Good - Masonry Fireplace in main level > (4)
>       TA	Average - Prefabricated Fireplace in main living area or Masonry Fireplace in basement > (3)
>       Fa	Fair - Prefabricated Fireplace in basement > (2)
>       Po	Poor - Ben Franklin Stove > (1)
>       NA	No Fireplace > (0)
		
* GarageType: Garage location > *"garage_type" / categorical / non ordinal*
		
>       2Types	More than one type of garage > (6)
>       Basment	Basement Garage > (5)
>       BuiltIn	Built-In (Garage part of house - typically has room above garage) > (4)
>       Attchd	Attached to home > (3)
>       Detchd	Detached from home > (2)
>       CarPort	Car Port > (1)
>       NA		No Garage > (0)
		
* GarageYrBlt: Year garage was built > *"garage_built_year" / numeric / integer*
		
* GarageFinish: Interior finish of the garage > *"garage_interior_finish" / categorical / ordinal*

>       Fin	Finished > (3)
>       RFn	Rough Finished > (2)	
>       Unf	Unfinished > (1)
>       NA	No Garage > (0)
		
* GarageCars: Size of garage in car capacity > *"garage_car_spaces" / numericla / integer*

* GarageArea: Size of garage in square feet > *"garage_size" / numerical / integer*

* GarageQual: Garage quality > *"garage_quality" / categorical / ordinal*

>       Ex	Excellent > (5) 
>       Gd	Good > (4)
>       TA	Typical/Average > (3)
>       Fa	Fair > (2)
>       Po	Poor > (1)
>       NA	No Garage > (0)
		
* GarageCond: Garage condition > *"garage_condition" / categorical / ordinal*

>       Ex	Excellent > (5)
>       Gd	Good > (4)
>       TA	Typical/Average > (3)
>       Fa	Fair > (2)
>       Po	Poor > (1)
>       NA	No Garage > (0)
		
* PavedDrive: Paved driveway > *"driveway_condition" / categorical / ordinal*

>       Y	Paved > (3)
>       P	Partial Pavement > (2)
>       N	Dirt/Gravel > (1)
		
* WoodDeckSF: Wood deck area in square feet > *"wood_deck_area" / numeric / integer*

* OpenPorchSF: Open porch area in square feet > *"porch_open_area" / numeric / integer*

* EnclosedPorch: Enclosed porch area in square feet > *"porch_enclosed_area" / numeric / integer*

* 3SsnPorch: Three season porch area in square feet > *"porch_three_season_area" / numeric / integer*

* ScreenPorch: Screen porch area in square feet > *"porch_screen_area" / numeric / integer*

* PoolArea: Pool area in square feet > *"pool_area" / numeric / integer*

* PoolQC: Pool quality > *"pool_quality" / categorical / ordinal*
		
>       Ex	Excellent > (4)
>       Gd	Good > (3)
>       TA	Average/Typical > (2)
>       Fa	Fair > (1)
>       NA	No Pool > (0)
		
* Fence: Fence quality > *"fence_quality" / categorical / ordinal*
		
>       GdPrv	Good Privacy > (4)
>       MnPrv	Minimum Privacy > (3)
>       GdWo	Good Wood > (2)
>       MnWw	Minimum Wood/Wire > (1)
>       NA	No Fence > (0)
	
* MiscFeature: Miscellaneous feature not covered in other categories > *"misc_feature" / categorical / non ordinal*
		
>       Elev	Elevator > (5)
>       Gar2	2nd Garage (if not described in garage section) > (4)
>       Othr	Other > (3)
>       Shed	Shed (over 100 SF) > (2)
>       TenC	Tennis Court > (1)
>       NA	None > (0)
		
* MiscVal: $Value of miscellaneous feature > *"misc_feature_value" / numeric / integer*

* MoSold: Month Sold (MM) > *"sale_month" / numeric / integer*

* YrSold: Year Sold (YYYY) > *"sale_year" / numeric / integer*

* SaleType: Type of sale > *"sale_type" / categorical / non ordinal*
		
>       WD 	Warranty Deed - Conventional > (10)
>       CWD	Warranty Deed - Cash > (9)
>       VWD	Warranty Deed - VA Loan > (8)
>       New	Home just constructed and sold > (7)
>       COD	Court Officer Deed/Estate > (6)
>       Con	Contract 15% Down payment regular terms > (5)
>       ConLw	Contract Low Down payment and low interest > (4)
>       ConLI	Contract Low Interest > (3)
>       ConLD	Contract Low Down > (2)
>       Oth	Other > (1)
		
* SaleCondition: Condition of sale > *"sale_condition" / categorical / non ordinal*

>       Normal	Normal Sale > (6)
>       Abnorml	Abnormal Sale -  trade, foreclosure, short sale > (5)
>       AdjLand	Adjoining Land Purchase > (4)
>       Alloca	Allocation - two linked properties with separate deeds, typically condo with a garage unit > (3)
>       Family	Sale between family members > (2)
>       Partial	Home was not completed when last assessed (associated with New Homes) > (1)

In [62]:
df_55_79 = df_55_79.rename({"Fireplaces": "fireplace_number",
                           "FireplaceQu": "fireplace_quality",
                           "GarageType": "garage_type",
                           "GarageYrBlt": "garage_built_year",
                           "GarageFinish":  "garage_interior_finish",
                           "GarageCars": "garage_car_spaces",
                           "GarageArea": "garage_size",
                           "GarageQual": "garage_quality",
                           "GarageCond": "garage_condition",
                           "PavedDrive": "driveway_condition",
                           "WoodDeckSF": "wood_deck_area",
                           "OpenPorchSF": "porch_open_area",
                           "EnclosedPorch": "porch_enclosed_area",
                           "3SsnPorch": "porch_three_season_area",
                           "ScreenPorch": "porch_screen_area",
                           "PoolArea": "pool_area",
                           "PoolQC": "pool_quality",
                           "Fence": "fence_quality",
                           "MiscFeature": "misc_feature",
                           "MiscVal": "misc_feature_value",
                           "MoSold": "sale_month",
                           "YrSold": "sale_year",
                           "SaleType": "sale_type",
                           "SaleCondition": "sale_condition"}, axis = 1)

df_55_79.head()

,fireplace_number,fireplace_quality,garage_type,garage_built_year,garage_interior_finish,garage_car_spaces,garage_size,garage_quality,garage_condition,driveway_condition,...,porch_screen_area,pool_area,pool_quality,fence_quality,misc_feature,misc_feature_value,sale_month,sale_year,sale_type,sale_condition
Id,,,,,,,,,,,,,,,,,,,,,
1,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
2,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
3,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
4,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
5,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [64]:
for col in df_55_79:
    print(f"{col}: \n {df_55_79[col].unique()}")

fireplace_number:
 [0 1 2 3]
fireplace_quality:
 [nan 'TA' 'Gd' 'Fa' 'Ex' 'Po']
garage_type:
 ['Attchd' 'Detchd' 'BuiltIn' 'CarPort' nan 'Basment' '2Types']
garage_built_year:
 [2003. 1976. 2001. 1998. 2000. 1993. 2004. 1973. 1931. 1939. 1965. 2005.
 1962. 2006. 1960. 1991. 1970. 1967. 1958. 1930. 2002. 1968. 2007. 2008.
 1957. 1920. 1966. 1959. 1995. 1954. 1953.   nan 1983. 1977. 1997. 1985.
 1963. 1981. 1964. 1999. 1935. 1990. 1945. 1987. 1989. 1915. 1956. 1948.
 1974. 2009. 1950. 1961. 1921. 1900. 1979. 1951. 1969. 1936. 1975. 1971.
 1923. 1984. 1926. 1955. 1986. 1988. 1916. 1932. 1972. 1918. 1980. 1924.
 1996. 1940. 1949. 1994. 1910. 1978. 1982. 1992. 1925. 1941. 2010. 1927.
 1947. 1937. 1942. 1938. 1952. 1928. 1922. 1934. 1906. 1914. 1946. 1908.
 1929. 1933.]
garage_interior_finish:
 ['RFn' 'Unf' 'Fin' nan]
garage_car_spaces:
 [2 3 1 0 4]
garage_size:
 [ 548  460  608  642  836  480  636  484  468  205  384  736  352  840
  576  516  294  853  280  534  572  270  890  772  319  240  250  271
  447  556  691  672  498  246    0  440  308  504  300  670  826  386
  388  528  894  565  641  288  645  852  558  220  667  360  427  490
  379  297  283  509  405  758  461  400  462  420  432  506  684  472
  366  476  410  740  648  273  546  325  792  450  180  430  594  390
  540  264  530  435  453  750  487  624  471  318  766  660  470  720
  577  380  434  866  495  564  312  625  680  678  726  532  216  303
  789  511  616  521  451 1166  252  497  682  666  786  795  856  473
  398  500  349  454  644  299  210  431  438  675  968  721  336  810
  494  457  818  463  604  389  538  520  309  429  673  884  868  492
  413  924 1053  439  671  338  573  732  505  575  626  898  529  685
  281  539  418  588  282  375  683  843  552  870  888  746  708  513
 1025  656  872  292  441  189  880  676  301  474  706  617  445  200
  592  566  514  296  244  610  834  639  501  846  560  596  600  373
  947  350  396  864  304  784  696  569  628  550  493  578  198  422
  228  526  525  908  499  508  694  874  164  402  515  286  603  900
  583  889  858  502  392  403  527  765  367  426  615  871  570  406
  590  612  650 1390  275  452  842  816  621  544  486  230  261  531
  393  774  749  364  627  260  256  478  442  562  512  839  330  711
 1134  416  779  702  567  832  326  551  606  739  408  475  704  983
  768  632  541  320  800  831  554  878  752  614  481  496  423  841
  895  412  865  630  605  602  618  444  397  455  409  820 1020  598
  857  595  433  776 1220  458  613  456  436  812  686  611  425  343
  479  619  902  574  523  414  738  354  483  327  756  690  284  833
  601  533  522  788  555  689  796  808  510  255  424  305  368  824
  328  160  437  665  290  912  905  542  716  586  467  582 1248 1043
  254  712  719  862  928  782  466  714 1052  225  234  324  306  830
  807  358  186  693  482  813  995  757 1356  459  701  322  315  668
  404  543  954  850  477  276  518 1014  753 1418  213  844  860  748
  248  287  825  647  342  770  663  377  804  936  722  208  662  754
  622  620  370 1069  372  923  192]
garage_quality:
 ['TA' 'Fa' 'Gd' nan 'Ex' 'Po']
garage_condition:
 ['TA' 'Fa' nan 'Gd' 'Po' 'Ex']
driveway_condition:
 ['Y' 'N' 'P']
wood_deck_area:
 [  0 298 192  40 255 235  90 147 140 160  48 240 171 100 406 222 288  49
 203 113 392 145 196 168 112 106 857 115 120  12 576 301 144 300  74 127
 232 158 352 182 180 166 224  80 367  53 188 105  24  98 276 200 409 239
 400 476 178 574 237 210 441 116 280 104  87 132 238 149 355  60 139 108
 351 209 216 248 143 365 370  58 197 263 123 138 333 250 292  95 262  81
 289 124 172 110 208 468 256 302 190 340 233 184 201 142 122 155 670 135
 495 536 306  64 364 353  66 159 146 296 125  44 215 264  88  89  96 414
 519 206 141 260 324 156 220  38 261 126  85 466 270  78 169 320 268  72
 349  42  35 326 382 161 179 103 253 148 335 176 390 328 312 185 269 195
  57 236 517 304 198 426  28 316 322 307 257 219 416 344 380  68 114 327
 165 187 181  92 228 245 503 315 241 303 133 403  36  52 265 207 150 290
 486 278  70 418 234  26 342  97 272 121 243 511 154 164 173 384 202  56
 321  86 194 421 305 117 550 509 153 394 371  63 252 136 186 170 474 214
 199 728 436  55 431 448 361 362 162 229 439 379 356  84 635 325  33 212
 314 242 294  30 128  45 177 227 218 309 404 500 668 402 283 183 175 586
 295  32 366 736]
porch_open_area:
 [ 61   0  42  35  84  30  57 204   4  21  33 213 112 102 154 159 110  90
  56  32  50 258  54  65  38  47  64  52 138 104  82  43 146  75  72  70
  49  11  36 151  29  94 101 199  99 234 162  63  68  46  45 122 184 120
  20  24 130 205 108  80  66  48  25  96 111 106  40 114   8 136 132  62
 228  60 238 260  27  74  16 198  26  83  34  55  22  98 172 119 208 105
 140 168  28  39 148  12  51 150 117 250  10  81  44 144 175 195 128  76
  17  59 214 121  53 231 134 192 123  78 187  85 133 176 113 137 125 523
 100 285  88 406 155  73 182 502 274 158 142 243 235 312 124 267 265  87
 288  23 152 341 116 160 174 247 291  18 170 156 166 129 418 240  77 364
 188 207  67  69 131 191  41 118 252 189 282 135  95 224 169 319  58  93
 244 185 200  92 180 263 304 229 103 211 287 292 241 547  91  86 262 210
 141  15 126 236]
porch_enclosed_area:
 [  0 272 228 205 176  87 172 102  37 144  64 114 202 128 156  44  77 192
 140 180 183  39 184  40 552  30 126  96  60 150 120 112 252  52 224 234
 244 268 137  24 108 294 177 218 242  91 160 130 169 105  34 248 236  32
  80 115 291 116 158 210  36 200  84 148 136 240  54 100 189 293 164 216
 239  67  90  56 129  98 143  70 386 154 185 134 196 264 275 230 254  68
 194 318  48  94 138 226 174  19 170 220 214 280 190 330 208 145 259  81
  42 123 162 286 168  20 301 198 221 212  50  99]
porch_three_season_area:
 [  0 320 407 130 180 168 140 508 238 245 196 144 182 162  23 216  96 153
 290 304]
porch_screen_area:
 [  0 176 198 291 252  99 184 168 130 142 192 410 224 266 170 154 153 144
 128 259 160 271 234 374 185 182  90 396 140 276 180 161 145 200 122  95
 120  60 126 189 260 147 385 287 156 100 216 210 197 204 225 152 175 312
 222 265 322 190 233  63  53 143 273 288 263  80 163 116 480 178 440 155
 220 119 165  40]
pool_area:
 [  0 512 648 576 555 480 519 738]
pool_quality:
 [nan 'Ex' 'Fa' 'Gd']
fence_quality:
 [nan 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']
misc_feature:
 [nan 'Shed' 'Gar2' 'Othr' 'TenC']
misc_feature_value:
 [    0   700   350   500   400   480   450 15500  1200   800  2000   600
  3500  1300    54   620   560  1400  8300  1150  2500]
sale_month:
 [ 2  5  9 12 10  8 11  4  1  7  3  6]
sale_year:
 [2008 2007 2006 2009 2010]
sale_type:
 ['WD' 'New' 'COD' 'ConLD' 'ConLI' 'CWD' 'ConLw' 'Con' 'Oth']
sale_condition:
 ['Normal' 'Abnorml' 'Partial' 'AdjLand' 'Alloca' 'Family']

In [65]:
df_55_79 = df_55_79.fillna(0)

display(df_55_79.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 1 to 1460
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fireplace_number         1460 non-null   int64
 1   fireplace_quality        1460 non-null   object
 2   garage_type              1460 non-null   object
 3   garage_built_year        1460 non-null   float64
 4   garage_interior_finish   1460 non-null   object
 5   garage_car_spaces        1460 non-null   int64
 6   garage_size              1460 non-null   int64
 7   garage_quality           1460 non-null   object
 8   garage_condition         1460 non-null   object
 9   driveway_condition       1460 non-null   object
 10  wood_deck_area           1460 non-null   int64
 11  porch_open_area          1460 non-null   int64
 12  porch_enclosed_area      1460 non-null   int64
 13  porch_three_season_area  1460 non-null   int64
 14  porch_screen_area        1460 non-null   int64
 15  pool_area                1460 non-null   int64
 16  pool_quality             1460 non-null   object
 17  fence_quality            1460 non-null   object
 18  misc_feature             1460 non-null   object
 19  misc_feature_value       1460 non-null   int64
 20  sale_month               1460 non-null   int64
 21  sale_year                1460 non-null   int64
 22  sale_type                1460 non-null   object
 23  sale_condition           1460 non-null   object
dtypes: float64(1), int64(12), object(11)
memory usage: 285.2+ KB

None

In [ ]:
display(df.reaplace({"fireplace_quality": {"Po": 1},
                     "garage_type": {"CarPort": 1},
                     "garage_interior_finish": {"Unf": 1},
                     "garage_quality": {"Po": 1},
                     "garage_condition": {"Po": 1},
                     "driveway_condition": {"N": 1},
                     "pool_quality": {"Fa": 1},
                     "fence_quality": {"MnWw": 1},
                     "misc_feature": {"TenC": 1},
                     "sale_type": {"Oth": 1},
                     "sale_condition": {"Partial": 1}})

In [52]:
display(df[df.garage_quality != df.garage_condition][["garage_quality", "garage_condition"]])

     garage_quality garage_condition
Id
9                Fa               TA
10               Gd               TA
30               Fa               TA
31               TA               Fa
40              NaN              NaN
...             ...              ...
1444             Fa               Po
1449             Fa               TA
1450            NaN              NaN
1451            NaN              NaN
1454            NaN              NaN

[140 rows x 2 columns]